################################################################################
#
# knulli-initramfs
#
################################################################################

KNULLI_INITRAMFS_VERSION = 1.36.1
KNULLI_INITRAMFS_SITE = http://www.busybox.net/downloads
KNULLI_INITRAMFS_SOURCE = busybox-$(KNULLI_INITRAMFS_VERSION).tar.bz2
KNULLI_INITRAMFS_LICENSE = GPLv2
KNULLI_INITRAMFS_LICENSE_FILES = LICENSE

KNULLI_INITRAMFS_DEPENDENCIES += host-uboot-tools libxcrypt
KNULLI_INITRAMFS_CFLAGS = $(TARGET_CFLAGS)
KNULLI_INITRAMFS_LDFLAGS = $(TARGET_LDFLAGS)

KNULLI_INITRAMFS_KCONFIG_FILE = \
    $(BR2_EXTERNAL_KNULLI_PATH)/package/boot/knulli-initramfs/busybox.config

INITRAMFS_DIR=$(BINARIES_DIR)/initramfs

# Allows the build system to tweak CFLAGS
KNULLI_INITRAMFS_MAKE_ENV = \
	$(TARGET_MAKE_ENV) \
	CFLAGS="$(KNULLI_INITRAMFS_CFLAGS)"
KNULLI_INITRAMFS_MAKE_OPTS = \
	CC="$(TARGET_CC)" \
	ARCH=$(KERNEL_ARCH) \
	PREFIX="$(INITRAMFS_DIR)" \
	EXTRA_LDFLAGS="$(KNULLI_INITRAMFS_LDFLAGS)" \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	CONFIG_PREFIX="$(INITRAMFS_DIR)" \
	SKIP_STRIP=n

KNULLI_INITRAMFS_KCONFIG_OPTS = $(KNULLI_INITRAMFS_MAKE_OPTS)

KNULLI_INITRAMFS_DEPENDENCIES += host-lz4
define KNULLI_INITRAMFS_BUILD_CMDS
	$(KNULLI_INITRAMFS_MAKE_ENV) $(MAKE) $(KNULLI_INITRAMFS_MAKE_OPTS) -C $(@D)
endef

ifeq ($(BR2_aarch64)$(BR2_TOOLCHAIN_OPTIONAL_LINARO_AARCH64),y)
KNULLI_INITRAMFS_INITRDA=arm64
else
KNULLI_INITRAMFS_INITRDA=arm
endif

# allwinner t527 u-boot workaround
ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_T527),y)
BATOCERA_INITRAMFS_INITRDA=arm
endif

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_SM8550),y)
KNULLI_INITRAMFS_DEPENDENCIES += firmware-armbian
define KNULLI_INITRAMFS_SM8550_EARLY_FIRMWARE
    mkdir -p $(INITRAMFS_DIR)/lib/firmware/qcom/sm8550/
    cp -R $(FIRMWARE_ARMBIAN_DIR)/qcom/sm8550/* \
        $(INITRAMFS_DIR)/lib/firmware/qcom/sm8550/
endef
KNULLI_INITRAMFS_PRE_INSTALL_TARGET_HOOKS += KNULLI_INITRAMFS_SM8550_EARLY_FIRMWARE
endif

define KNULLI_INITRAMFS_INSTALL_TARGET_CMDS
	mkdir -p $(INITRAMFS_DIR)
	cp $(BR2_EXTERNAL_KNULLI_PATH)/package/boot/knulli-initramfs/init \
	    $(INITRAMFS_DIR)/init
	$(KNULLI_INITRAMFS_MAKE_ENV) $(MAKE) $(KNULLI_INITRAMFS_MAKE_OPTS) -C $(@D) install
	(cd $(INITRAMFS_DIR) && find . | cpio -H newc -o > $(BINARIES_DIR)/initrd)
	(cd $(BINARIES_DIR) && mkimage -A $(KNULLI_INITRAMFS_INITRDA) \
	    -O linux -T ramdisk -C none -a 0 -e 0 -n initrd -d ./initrd ./uInitrd)
	$(COMPRESSION_TYPE_COMMAND)
endef

$(eval $(kconfig-package))
