#!/bin/sh

DAEMON="splash-mpv"

case "$1" in
    start)
        printf 'Starting %s: ' "$DAEMON"
        if [ -x /usr/bin/knulli-console-motd ]; then
            /usr/bin/knulli-console-motd &
            echo "OK"
        else
            echo "MISSING"
        fi
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
        ;;
esac

exit 0
