#!/bin/sh

case "$1" in
    start)
        [ -x /usr/bin/knulli-boot-status ] && \
            /usr/bin/knulli-boot-status "Starting system services" >/dev/null 2>&1 || true
        ;;
    stop)
        [ -x /usr/bin/knulli-boot-status ] && \
            /usr/bin/knulli-boot-status "System services ready" >/dev/null 2>&1 || true
        ;;
esac

exit 0
